json.id         boat.id
json.name       boat.name
json.maker      boat.maker
json.model      boat.model
json.year       boat.year
json.specs      boat.specs
json.pricing    boat.pricing
json.created_at boat.created_at
json.updated_at boat.updated_at